### PR TITLE
open camera with android 12.RD-19607

### PR DESCRIPTION
**Pull request by dhouha123**

### CODE REVIEW

**Comment by waelba** [comment]
I discovered a bug.
If I have another camera application (not the default application) installed and I deactivate the default camera application, the screen remains gray

https://user-images.githubusercontent.com/6080628/135846825-5ab02488-5fec-41b8-aedf-7fd942ade3a3.mp4

I tested an old android version (api 29) and we have a dialogue with different cameras installed on the device.
camera

Possible to do the same @dhouha123 ?

**Comment by CedricBm** [comment]
1. We have this dialogue in an old version of our sample app? 
2. I thought we used an "embedded" version of the camera in our SDK, a bit like FB messenger, don't we? @waelba are you suggesting to change this behavior?

**Comment by waelba** [comment]
We already have this dialogue in an old version of our sample app so if it's possible to keep it

**Comment by CedricBm** [comment]
ah ok then, if it's to keep the existing behavior :+1:

**Comment by dhouha123** [comment]
android new version will force apps to use your phone's default camera but I want to check if I can use a custumAlert to propose all camera applications

**Comment by CedricBm** [comment]
Ok, well if the default is always the default camera, I guess it's acceptable. I doubt people disallow the camera permission on their camera default app. But maybe this is a real usecase when people install multiple camera apps.

I let you investigate when you'll have more time. And don't forget to add a section in the SDK readme.

**Comment by dhouha123** [comment]
ok after merge that I want to update the readme

**Comment by CedricBm** [comment]
IMO it's simpler if you prepare the readme MR along this current sample app change. But as you wish, as long as we don't forget.

**Comment by waelba** [comment]
To update the sample app to android 12 (https://github.com/ringcentral-tutorials/engage-digital-messaging-android-demo/pull/21) we must merge this MR first

**Comment by dhouha123** [comment]
after some search starting android 11, we can't open external camera app: 
https://developer.android.com/about/versions/11/behavior-changes-11#camera

**Comment by waelba** [comment]
Ok so I think we can ignore my remark. Thanks @dhouha123 !

**Comment by CedricBm** [comment]
Cool, does this mean we can merge this and update the readme?

**Comment by dhouha123** [comment]
I think yes

**Pull request merged**
