### PR TITLE
Fixed: clicking on message notification opens the Android App main me…

### PR DESCRIPTION
**Pull request by dhouha123**

### CODE REVIEW

**Comment by waelba** [comment]
LGTM

**Comment by CedricBm** [comment]
FTR push notifications didn't work for me on the test apk.

**Comment by dhouha123** [comment]
I will regenerate the apk because it work for me

**Comment by CedricBm** [comment]
LGTM now :)

**Comment by dhouha123** [comment]
I will merge this after the RD-17353

**Pull request merged**
